# CONFIGURACIÓN EXCLUSIVA PARA EL AMBIENTE DE PRUEBAS (TEST)
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/db_ms_clientes_test?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Santiago&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=

# Estrategia de creación para pruebas (crea las tablas al iniciar y las destruye al finalizar)
spring.jpa.hibernate.ddl-auto=create-drop

# Mantener la consola limpia durante la ejecución de los tests
spring.jpa.show-sql=false
logging.level.root=WARN