# ===================================================================
# CONFIGURACIÓN EXCLUSIVA PARA EL AMBIENTE DE DESARROLLO (DEV)
# ===================================================================

# Base de datos: Apunta al esquema de desarrollo en Laragon
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/db_ms_clientes_dev?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Santiago&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=

# Hibernate en Desarrollo: Se limita a VALIDAR lo que creó Flyway sin alterar las tablas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# CONFIGURACIÓN DE LOGS INTELIGENTE (Limpiamos el ruido en consola)
logging.level.root=INFO