spring.application.name=ms-reservas

# ===============================
# CONFIGURACIÓN DEL SERVIDOR
# ===============================
server.port=8083

# ===============================
# CONFIGURACIÓN DE BASE DE DATOS
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3307/prueba2?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

# ===============================
# CONFIGURACIÓN DE JPA Y FLYWAY
# ===============================
# validate: Hibernate solo verifica, NO crea tablas. Flyway será el encargado.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Activar Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# ===============================
# LOGS (SLF4J)
# ===============================
logging.level.com.example.ms_reservas=INFO