# Indicar el perfil activo por defecto
spring.profiles.active=dev
spring.application.name=ms-reservas

# Configuración común de Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Documentación OpenAPI/Swagger (Estandarizada para pasar por el API Gateway)
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
server.forward-headers-strategy=FRAMEWORK