server.address=0.0.0.0
server.port=8083

# BASE DE DATOS DE PRUEBAS
spring.datasource.url=jdbc:h2:mem:prueba2_test;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

# Se desactivan migraciones en test para agilizar JUnit
spring.flyway.enabled=false

logging.level.root=WARN