spring.profiles.active=dev
spring.application.name=ms-reservas
server.port=8083

# CONFIGURACIÓN DE BASE DE DATOS (Ajustada para Laragon)
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/prueba2?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Santiago&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# CONFIGURACIÓN DE JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

# MIGRACIONES CON FLYWAY
spring.flyway.enabled=true
spring.flyway.locations=classpath:db_migration

# CONEXIÓN A EUREKA SERVER
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# CONFIGURACIÓN SWAGGER / OPENAPI (Estandarizada para API Gateway)
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs

# ESTRATEGIA DE PROXY (Necesaria para que el Gateway encamine bien las peticiones)
server.forward-headers-strategy=framework

logging.level.root=INFO