spring.application.name=ms-pagos
server.port=8084
# Perfil activo por defecto
spring.profiles.active=dev

# Configuración de Eureka Client (común)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true