# Base de datos de Testing (Idealmente en memoria o separada)
spring.datasource.url=jdbc:mysql://localhost:3306/pagos_test?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Flyway (Apagado en test si usamos create-drop, o encendido si quieres la misma estructura)
spring.flyway.enabled=false