spring.application.name=ms-reportes
server.port=8087

# Perfil activo por defecto
spring.profiles.active=dev

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Swagger / OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

# Estrategia para pasarelas
server.forward-headers-strategy=framework

logging.level.root=INFO