spring.application.name=ms-empleados
spring.profiles.active=dev
server.port=8086

# CONFIGURACIÓN DE JPA / HIBERNATE BASE
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

# CONEXIÓN A EUREKA SERVER
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# CONFIGURACIÓN SWAGGER / OPENAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/doc/swagger-ui.html

# ESTRATEGIA DE PROXY (Para API Gateway)
server.forward-headers-strategy=framework