# CONFIGURACIÓN DE BASE DE DATOS (Laragon)
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/prueba1?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Santiago&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# HIBERNATE DDL
# ¡IMPORTANTE! Como estamos usando db/migration (Flyway), esto debe ser 'validate' para que Hibernate no cree las tablas antes que Flyway.
spring.jpa.hibernate.ddl-auto=validate

# RED Y LOGS
server.address=0.0.0.0
logging.level.root=DEBUG