server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-clientes-route
          uri: lb://ms-clientes
          predicates:
            - Path=/api/clientes/**

        - id: ms-empleados-route
          uri: lb://ms-empleados
          predicates:
            - Path=/api/v1/empleados/**

        - id: ms-pagos-route
          uri: lb://ms-pagos
          predicates:
            - Path=/api/pagos/**

        - id: ms-reportes-route
          uri: lb://ms-reportes
          predicates:
            - Path=/api/v1/reportes/**

        - id: ms-reservas-route
          uri: lb://ms-reservas
          predicates:
            - Path=/api/v1/reservas/**, /api/v1/estados-reserva/**

        - id: ms-sucursales-route
          uri: lb://ms-sucursales
          predicates:
            - Path=/api/v1/sucursales/**

        - id: ms-vehiculos-route
          uri: lb://ms-vehiculos
          predicates:
            - Path=/api/vehiculos/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
