spring.application.name=ms-sucursales



# CONFIGURACIÓN DEL SERVIDOR
# Puerto exigido para ms-sucursales
server.port=8085


# CONFIGURACIÓN DE BASE DE DATOS
# Conexión a la BD 'prueba1'. createDatabaseIfNotExist la crea automáticamente si no existe.
spring.datasource.url=jdbc:mysql://localhost:3307/prueba1?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# CONFIGURACIÓN DE JPA / HIBERNATE
# Actualiza las tablas automáticamente basándose en tus entidades @Entity
spring.jpa.hibernate.ddl-auto=update
# Muestra por consola las consultas SQL que hace por debajo
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# LOGS (SLF4J)
# Activa los logs informativos para tu paquete principal
logging.level.com.example.ms_sucursales=INFO
