spring.application.name=ms-sucursales
spring.profiles.active=dev
server.port=8085
server.address=0.0.0.0

# CONEXIÓN A EUREKA SERVER
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# CONFIGURACIÓN SWAGGER / OPENAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# ESTRATEGIA DE PROXY (Para API Gateway)
server.forward-headers-strategy=framework