# Definir el perfil activo por defecto
spring.profiles.active=dev

# Parámetros comunes del microservicio de vehículos
spring.application.name=MS-VEHICULOS
server.port=8082

# Conexión a Eureka Server (Común para tdo el ecosistema)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Configuración Swagger / OpenAPI (Estandarizada para el API Gateway)
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs

# Estrategia de Proxy para el enrutamiento correcto
server.forward-headers-strategy=framework

# CRÍTICO: Esperar a que Hibernate cree las tablas antes de ejecutar el DataInitializer
spring.jpa.defer-datasource-initialization=true